# Generated by Django 4.2.6 on 2023-10-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vizcab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vizcab.constructionproduct",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vizcab.zone"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="zone",
            name="products",
            field=models.ManyToManyField(
                through="vizcab.ZoneProduct", to="vizcab.constructionproduct"
            ),
        ),
    ]
