# Generated by Django 4.2.6 on 2023-10-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizcab', '0002_zoneproduct_zone_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='usage',
        ),
    ]
